openapi: 3.0.0
info:
  title: API Asistente - Cognitiva
  version: '1.0'
  description: "Esta documentación hace referencia a API's que son utilizadas por clientes para integrarse con Cognitiva para hacer uso del Asistente Cognitivo.\nLa referencia aquí expuesta es para clientes que cuentan con una API Key entregada por Cognitiva para el uso de las API's . \n"
  contact:
    name: Soporte Chile
    url: 'https://cognitivacl.zendesk.com/'
    email: soporte_chile@cognitiva.la
servers:
  - url: 'https://ambiente-cliente.mycognitiva.io/mad'
paths:
  /external_message:
    parameters: []
    post:
      summary: Enviar mensaje
      description: Recibe mensaje desde integración WhatsApp para ser respondido por Asistente Cognitivo.
      security:
        - API Key: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cid:
                  description: ID de Conversation
                  type: string
                id_cliente:
                  type: string
                  description: ID de cliente.
                msg:
                  type: string
                  description: Texto que será entregado a Asistente Cognitivo.
                token:
                  type: string
                  description: Marca de tiempo para fines estadísticos.
                tipo_canal:
                  type: integer
              required:
                - cid
                - msg
                - tipo_canal
            examples:
              Ejemplo:
                value:
                  cid: null
                  id_cliente: '1'
                  location: ''
                  msg: 'Hola, estoy resfriado, necesito ayuda, qué me recomiendas?'
                  token: ''
                  tipo_canal: 4
        description: |
          Parámetros necesarios para derivar mensaje a Asistente.
          Para tipo_canal usar los siguientes valores enteros.

          **Tipo de canal**


          | id | Tipo canal  |
          |---|---|
          | 1  | Web  |
          | 2  | Facebook  |
          | 3  | Teams  |
          | 4 |  WhatsApp |
          |  5 |Mobile   |
          |  6 |Voz|
      parameters: []
      responses:
        '200':
          description: |
            Respuesta estándar cuando un mensaje es recibido y entregado a asistente Cognitivo.
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  estado:
                    type: object
                    properties:
                      codigoEstado:
                        type: string
                      glosaEstado:
                        type: string
                  general:
                    type: object
                    properties:
                      cid:
                        type: string
                      nodo_id:
                        type: object
                        properties:
                          _node_output_map:
                            type: object
                            properties:
                              Bienvenido:
                                type: object
                              node_id_number:
                                type: object
                              response_id_number:
                                type: object
                          dialog_request_counter:
                            type: string
                          dialog_stack:
                            type: array
                            items:
                              type: object
                              properties:
                                dialog_node:
                                  type: string
                          dialog_turn_counter:
                            type: number
                          initialized:
                            type: boolean
                    required:
                      - cid
                  like:
                    type: boolean
                  msg:
                    type: array
                    items:
                      type: string
                  buttons:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        value:
                          type: string
                required:
                  - msg
              examples:
                Respuesta con canal:
                  value:
                    buttons:
                      - title: Productos Personas
                        value: Productos Personas
                      - title: Productos Empresas
                        value: Productos Empresas
                    estado:
                      codigoEstado: 200
                      glosaEstado: ok
                    general:
                      cid: f376fc93-0ea5-48de-b24c-d2b6632872d1
                      nodo_id:
                        _node_output_map:
                          Bienvenido:
                            '0':
                              - 0
                          node_4_1575298698266:
                            '0':
                              - 0
                        dialog_request_counter: 2
                        dialog_stack:
                          - dialog_node: node_4_1575298698266
                        dialog_turn_counter: 2
                        initialized: true
                      tipo: ''
                    like: false
                    msg:
                      - 'Tenemos productos para personas y empresas. Elige una categoría para ver productos asociados: '
                Canal con KillSwitch:
                  value:
                    estado:
                      codigoEstado: 200
                      glosaEstado: ok
                    general:
                      cid: null
                      nodo_id: null
                      tipo: null
                    like: null
                    msg:
                      - 'Actualmente estamos generando una actualización en nuestro asistente, por favor intente más tarde.'
                Respuesta Genérica:
                  value:
                    estado:
                      codigoEstado: 200
                      glosaEstado: ok
                    general:
                      cid: fc778565-a69c-40bc-83ca-c476a6951aee
                      nodo_id:
                        _node_output_map:
                          Bienvenido:
                            '0':
                              - 0
                          node_2_1576093773307:
                            '0':
                              - 0
                        branch_exited: true
                        branch_exited_reason: completed
                        dialog_request_counter: 2
                        dialog_stack:
                          - dialog_node: root
                        dialog_turn_counter: 2
                        initialized: true
                      tipo: ''
                    like: false
                    msg:
                      - respuesta WEB
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              examples:
                Ejemplo:
                  value:
                    estado:
                      codigoEstado: 400
                      glosaEstado: Error en el tipo de dato canal
                    respuesta: null
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              examples:
                Response:
                  value:
                    response: 'No autorizado para la request. '
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              examples:
                Response:
                  value:
                    response: 'Request no encontrado. '
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
              examples:
                Response:
                  value:
                    response: 'Error en el servidor. '
        '':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: Enviar mensaje a Asistente
components:
  securitySchemes:
    API Key:
      name: API Key
      type: apiKey
      in: query
      description: API Key proporcionada por Cognitiva para hacer uso de los endpoints públicos.

